all:
  hosts:
    rocky1:
      ansible_host: 10.0.5.75
      static_ip: 10.0.5.10
      new_hostname: rocky1
    rocky2:
      ansible_host: 10.0.5.77
      static_ip: 10.0.5.11
      new_hostname: rocky2
    rocky3:
      ansible_host: 10.0.5.76
      static_ip: 10.0.5.12
      new_hostname: rocky3
  vars:
    ansible_user: root
    ansible_password: Ch@mpl@1n!25
