<<<<<<< HEAD
servers:
  hosts:
    dc-blue1:
      ansible_host: 10.0.5.5
      ansible_user: Administrator
      ansible_password: "Ch@mpl@1n!25"
      ansible_connection: winrm
      ansible_port: 5985
=======
all:
  servers:
    hosts:
      dc-blue1:
        ansible_host: 10.0.5.5
        ansible_user: Administrator
        ansible_password: "URPASSHERE"
        ansible_connection: winrm
        ansible_port: 5985
>>>>>>> 9f4eea3320ea4fac180e8e5373fb38c7aa24c673
